version: '3.7'

services:
  app:
    build: .
    command: gunicorn events_manager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - dist:/app/dist
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  redis:
    image: redis
    restart: always
    container_name: 'redis_server'
    command: redis-server
    ports:
      - '6379:6379'
  celery:
    build: .
    restart: always
    container_name: 'celery_worker'
    command: celery -A events_manager worker --loglevel=info
    links:
      - redis
    env_file:
      - .env
    depends_on:
      - app
      - redis
  nginx:
    build: ./backend/nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/staticfiles
      - dist:/app/dist
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:
  dist: